### PR TITLE
Refactor react app

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
I refactored the react app to use some more advanced data handling so it will poll and be more responsive when adding tickets. I mainly did this for the version in cloud-staging since the update is a little slower there and it might look like nothing happened without the polling.

### CODE REVIEW

**Comment by gamerson** [comment]
Thanks Allen, so this version is running on the cloud staging uat? 

So just to confirm, we don't need to use this version tomorrow necessarily, but its here to save for future.

**Comment by allen-ziegenfus** [comment]
@gamerson  Yes. it's working locally too but depending on how much risk you want to take on for the workshop we might want to just go with what we already have for that.

**Comment by gamerson** [comment]
ok, so for tomorow we will stand pat.  But we can merge this just afterwards, because I feel this repo will have a lifespan after this devcon.

**Comment by gamerson** [comment]
ok, so for tomorow we will stand pat.  But we can merge this just afterwards, because I feel this repo will have a lifespan after this devcon.

**Pull request merged**
